[versions]
kotlin = "2.3.10"
micronaut = "4.10.15"
micronaut-plugin = "4.6.2"
minestom = "1058d88552"
logback = "1.5.29"
shadow-plugin = "9.3.1"
worldseed = "11.5.6"
plasmovoice = "2.1.8"

[libraries]
micronaut-inject = { module = "io.micronaut:micronaut-inject", version.ref = "micronaut" }
micronaut-runtime = { module = "io.micronaut:micronaut-runtime", version.ref = "micronaut" }
micronaut-inject-java = { module = "io.micronaut:micronaut-inject-java", version.ref = "micronaut" }

minestom = { module = "net.minestom:minestom-snapshots", version.ref = "minestom" }
worldseed = { module = "net.worldseed.multipart:WorldSeedEntityEngine", version.ref = "worldseed" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

plasmovoice = { module = "su.plo.voice.api:server", version.ref = "plasmovoice" }
plasmovoice-minestom = { module = "su.plo.voice.server:minestom", version.ref = "plasmovoice" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }
